### ISSUE TITLE
Path type should be PathBuf or &Path, not &str

### ISSUE THREAD

**Issue by sffc** [iddohau/rust-strings#1]
The standard type in Rust for dealing with filesystem paths is `&Path`, or `PathBuf` for a fully-owned version. In order to interface with `rust_strings`, users need to convert their `&Path` to a `String`, which is a lossy operation since the Path need not be UTF-8 (though it often is).

CC @robertbastian

**Comment by iddohau** [comment]
Hi @sffc,
Changing `String` to `&Path` make sense.
I will probably do this in the next few days.
Thanks for checking my repository 😄

**Comment by iddohau** [comment]
I have released new version containing this change 😄
