### ISSUE TITLE
Allow comilation using pip wheel

### ISSUE THREAD

**Issue by Krakoer** [iddohau/rust-strings#44]
Hi,

Adding a [tool.maturin] section in the pyproject.toml with 
```
profile = "release"
features = ["python_bindings"]
```

would allow for custom build using the `pip wheel` command.

Context: My project's CI builds the dependencies using the `pip wheel` command on an alpine container, and without this [tool.maturin] section the project builds without the python bindings. 

Thank for your work!

**Comment by iddohau** [comment]
Hi,
This sounds like a good idea.
Do you want to open a pull request with the change?

**Comment by iddohau** [comment]
Closing this issue as the pull request with the desired changed has been merge.
Thank you for your contribution 😀
https://github.com/iddohau/rust-strings/pull/45
