### ISSUE TITLE
Is a min_length of 1 Invalid?

### ISSUE THREAD

**Issue by judgeman5** [iddohau/rust-strings#59]
I've been working with the library, and when I input the min_length to 1, it doesn't seem to return any data. A min length of 2 seems to work fine, but just curious if this is correct behavior.

When I try to do a min length of 1 with the strings command on Linux, it works.

**Comment by iddohau** [comment]
Hi,
This is indeed a bug and not the correct behavior.
I've fixed it, just update to version 0.6.0.
